### ISSUE TITLE
cjdroute stops routing packets after reboot (Win 8)

### ISSUE THREAD

**Issue by ghost** [interfect/cjdns-installer#3] opened 2015-04-26 15:43 UTC
I'm running the latest version (0.3-proto14), but it happened with the previous version too. System is Windows 8 Pro x64, internet connection over wifi.

cjdns routes packets when it's first installed, but stops after rebooting or going into standby. It's supposedly peered to my VPS, but I can't ping it from there (and all my other personal peers on the VPS can connect to Hype like normal). This makes me suspect it may be a problem with the TAP driver.

**Comment by interfect** [comment] 2015-04-27 02:23
Have you tried looking at the cjdns logging output (on the admin RPC port,
maybe from another computer where cjdnslog is happier running) while this
is happening?

Have you tried a "net stop cjdns" and "net start cjdns"?

Do you have VirtualBox or something else that uses TUN/TAP devices?

I can rebuild the installer for the latest cjdns (which I ought to do
anyway), but if cjdns is starting up and running and for some reason can't
route, then it's a cjdns bug rather than an installer bug. In that case, if
it still happens with the latest build for Windows (which you can just
build according to the wiki and drop in over the cjdns.exe that the
installer installs, for testing), the bug report would probably live at <
https://github.com/hyperboria/cjdns/issues>.

**Comment by ghost** [comment] 2015-04-27 22:37
I have tried restarting cjdns manually, but it doesn't help.

Virtualbox is installed, but disabling all of its network interfaces also doesn't change anything, and neither does uninstalling it entirely.

The Event Viewer logs are just messages indicating that cjdns has stopped or started successfully. No errors to be found.

I've discovered that after leaving standby/rebooting, no Hype addresses resolve; but when I restart the service manually, the addresses resolve, but time out before anything loads. I'm not sure what this indicates, but I think it means that cjdroute is working out the route for the packets to take just fine, but maybe not actually sending the packets? I think I may be in over my head, I dunno.

**Comment by interfect** [comment] 2015-04-28 01:50
The cjdns log output (from the "cjdnslog" tool in the main cjdns repo)
would be useful to have.

DNS issues may have to do with whether your computer thinks you have IPv6
connectivity, depending on what you are using to do the resolving. A
straight resolver that goes and hits a clearnet DNS server really ought to
get the same answer whether cjdns is working or not, but browsers will
often cheat and check to see that you actually have Internet IPv6 before
accepting IPv6 addresses from DNS.

So the problem is that cjdns is not routing on boot or after standby? Like
you boot up/wake from standby and go to ping your peer by IPv6 in the cmd
window, and it doesn't work?

Is there something you have to do to get it working again? Or has it never
worked except for immediately after the initial install?

Does it by any chance start working after leaving it sitting on for an hour?

**Comment by interfect** [comment] 2017-03-09 03:01
I'm going to close this issue because it's old, and I haven't got a Win8 machine to try and reproduce it.

**Closed as completed by interfect** 2017-03-09 03:01 UTC
